name: Process CSV with R

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v1

    - name: Install packages
      run: |
        R -e 'install.packages(c("dplyr", "readr", "magrittr", "googledrive"))'

    - name: Run R script
      env:
        GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
      run: |
        echo "$GDRIVE_CREDENTIALS" > credentials.json
        Rscript practica_kantar.R ${{ github.event.inputs.file_id }}
