name: Process CSV with R

on:
  workflow_dispatch:
    inputs:
      file_id:
        description: 'The path of the CSV file on Dropbox to process'
        required: true

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Update to use v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2  # Update to use v2
      with:
        r-version: '4.2.0'  # Use a compatible version of R

    - name: Install packages
      run: |
        R -e 'install.packages(c("dplyr", "readr", "magrittr", "httr"))'

    - name: Run R script
      env:
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
      run: |
        Rscript practica_kantar.R ${{ github.event.inputs.file_id }}

